### ISSUE TITLE
Path for pact tools should not be hard-coded

### ISSUE THREAD

**Issue by stuartmurray-form3** [form3tech-oss/go-pact-testing#28]
# Overview

* The path to the pact server is hard-coded: https://github.com/form3tech-oss/go-pact-testing/blob/master/pacttesting/testing.go#L148.
* If we store the pact server executable at the root of our project (`./pact`), then this is fine.
* If we move it for any reason, for example to `./tools/pact`, then e.g. `./tools/pact/bin/pact-mock-service` will not be found and so `go-pact-testing` will not work properly.
* It should be possible to specify a path or, if hard-coded, we should use `./tools/pact`

**Comment by joshua-hill-form3** [comment]
I'm in favour of a non-breaking change that allows the path to the pact server executable to be configured.

**Comment by georgijd-form3** [comment]
We have just hit this problem. The issue we faced is that the pact tool is now installed (via the build scripts) under `tools/pact/bin` whereas this library expects it under `pact/bin`

To workaround it we added a new Makefile target to create a symlink:

```Makefile
.PHONY: fix-pact-path
fix-pact-path:
        @echo "Fixing pact path by symlinking tools/pact/ to pact/"
        @ln -sf tools/pact pact
```

Obviously this is not ideal and it would be great if the path to the pact server was configurable

**Comment by georgijd-form3** [comment]
Looks like this was resolved in https://github.com/form3tech-oss/go-pact-testing/pull/31
